papers/utils.py
Hi there,
Here is my first contribution _officially_ to Dissemin! :tada:
Unfortunately, it is nothing incredible :sob: !
I figured that the most simple way to start contributing to Dissemin was to start from utilities and unit tests which were self-explanatory.
I think that documenting my journey in the codebase would be cool for future contributors and people who desire to contribute to Dissemin. Accompanying them is also a way to encourage them to throw their pull requests away, even if those are wrong, not really documented or bad written.
So there is always something to do for the next contributor.
It sounds like that Travis said that I didn't break any tests. Let me know if it looks good for you and :rocket: !
=> Papers utilities code cleanup (readability)

doc/sphinx/install.rst
Usually, when a contributor wants to start working on Dissemin, he'll follow the docs.
And, at a certain point, try to log in and find himself unable to do so :/
Thanks to @wetneb who walked me through the steps. I hope it'll help! (warning: didn't test if the markup is okay).
=> How to set up sandbox ORCID (docs)

papers/testutils.py, papers/utils.py
We just want to reverse the order when we have diacritics and then, we normalize back.
Closes #147
=> Fix accents with diacritics in titles

backend/orcid.py, locale/fr/LC_MESSAGES/djangojs.po, notification/migrations/0003_auto_20160516_0045.py, papers/static/papers/refresh.js, papers/static/style/style.css, requirements_frontend.txt, requirements_frontend_light.txt
Now, Dissemin should be more user-friendly when searching for a researcher's papers.
=> Add reason for why Dissemin skipped a paper

backend/orcid.py, backend/papersource.py
=> Use local researcher name as fallback for papers which are ignored

dissemin/settings/common.py, dissemin/urls.py, locale/fr/LC_MESSAGES/django.po, papers/static/style/style.css, templates/dissemin/skeleton.html
Resolves #205.
Also makes the footer a container.
=> Add language switch

.travis.yml, dissemin/settings/.gitignore, dissemin/settings/common.py, dissemin/settings/dev.py, dissemin/settings/search_engine_template.py, dissemin/urls.py, doc/sphinx/install.rst, papers/static/style/style.css, papers/templates/papers/index.html, papers/templatetags/statuses.py, publishers/forms.py, publishers/search_indexes.py, publishers/templates/publishers/list.html, publishers/templates/search/indexes/publishers/publisher_text.txt, publishers/urls.py, publishers/views.py, requirements_frontend.txt, requirements_frontend_light.txt, templates/dissemin/details.html
Resolves #193.
Some things are still to do:
- Update the docs about installing a search backend. For development, `whoosh` works okay; basic options are already in `settings/dev.py` but I'm not sure if it is fine to add it to `requirements_frontend.txt`. Don't forget to call `manage.py update-index` at some point.
- Translations
- I might have broken some styling somewhere.
=> Add search in publishers.

.travis.yml, deposit/urls.py, dissemin/urls.py, papers/ajax.py, papers/api.py, papers/urls.py, publishers/urls.py, requirements_frontend.txt, requirements_frontend_light.txt, upload/urls.py
@RaitoBezarius any comments?
I'm so excited, this will enable JSON fields! Then I'll merge Author and OaiRecord into Paper as JSON!
=> Migrate to Django 1.9

dissemin/settings/common.py, locale/fr/LC_MESSAGES/django.po, publishers/templates/publishers/list.html, requirements_frontend.txt, requirements_frontend_light.txt
"Sort by (increasing|decreasing) (name|popularity)" → "Trier par (nom|popularité) (croissant(e)|décroissant(e))"
=> Proper translation of sort order

statistics/static/showStats.js
=> Make statistics numbers more readable

papers/baremodels.py, papers/models.py, papers/name.py, papers/testbare.py, papers/testnames.py
=> Fix some bugs requiring a reimport

backend/crossref.py, backend/oai.py, backend/testoai.py, papers/forms.py, papers/name.py, papers/search_indexes.py, papers/testbare.py, papers/testnames.py, papers/utils.py
=> Fix most problems that need a reimport of the papers

statistics/static/showStats.js
As mentioned in the last summary by @wetneb  :)
=> Round statistics numbers and show K rather than k

papers/models.py, papers/templates/papers/paperDetails.html
This adds a link to the OAB request for each unavailable paper, next to the Google Scholar link.
Cc: @JosephMcArthur
=> Add OAB link to unavailable papers

front/css/style.css, papers/static/style/style.css, templates/dissemin/skeleton.html
Better alignment of the change lang form in the footer on small screens.
Closes #375.
Also make the email link clickable in the footer.
=> Fix footer on small screens

doc/tutorial/basic-hack.md
Tutorials of this type may help a newbie to hack dissemin.
As it is a markdown file, it can easily be served as github pages.
Please note that the tutorial is not self sufficient as I somehow correspond to this "newbie" profile ;)
=> [add] basic tutorial to learn to hack dissemin

papers/templates/papers/paperDetails.html
See https://github.com/OAButton/discussion/issues/790
=> [fix] change OAB URL to stable and https

.travis.yml
Codacy rocks: https://www.codacy.com/app/dissemin/dissemin/dashboard
It seems to have better GitHub integration than Coveralls, and includes some code review features. And lots of fancy metrics. <3
=> Switch to Codacy for coverage and code review

locale/fr/LC_MESSAGES/django.po
=> Fix typos in French translation

deposit/hal/admin.py, deposit/osf/admin.py
This lets admins inspect the deposit preferences of users - something I wanted to do today.
=> Register preference models in admin

deposit/hal/models.py, deposit/protocol.py, doc/sphinx/repository_interfaces.rst
the strings with '__' are not correctly picked up
(Thanks to Chinese, it's now very easy to notice these strings!)
=> always use '_' instead of '__' for localization

deposit/zenodo/forms.py, deposit/zenodo/tests.py
=> Change Zenodo default license to zenodo-freetoread-1.0

backend/orcid.py, backend/testorcid.py, backend/tests.py, baretest.sh, dissemin/fasttestrunner.py, papers/orcid.py, papers/testorcid.py, test.sh
=> Move to ORCID v2.1 API

backend/testorcid.py, papers/templates/papers/search.html, papers/testorcid.py
I could not reproduce #344, it might have been solved by the ORCID work I have done this week-end.
=> Add test witnessing the fix for #344

templates/dissemin/skeleton.html
Adapts the language on the root element.
=> Fix language on root HTML element. Closes #464

.travis.yml, README.md, templates/dissemin/skeleton.html
=> Reactivate Coveralls for Coverage

backend/crossref.py, backend/maintenance.py, backend/oadoi.py, backend/testoai.py, dissemin/settings/common.py, papers/models.py
This makes Dissemin comply with the crossref politeness guidelines (see https://github.com/CrossRef/rest-api-doc#good-manners--more-reliable-service )
=> Polite crossref

dissemin/settings/common.py
Add new language in main page (Change language list).
=> Add new language

doc/sphinx/datasources.rst
=> add link to BASE source list

front/css/style.css, papers/static/style/style.css, templates/dissemin/skeleton.html
Hi,
Here is a PR matching https://github.com/dissemin/dissemin/issues/530. I'm not super used to editing Dissemin files, I hope I did it right.
First commit is the deletion of left padding in footer and rework of language switch form, as written in https://github.com/dissemin/dissemin/issues/530#issue-330255781.
Second commit is optional and expands the list in the footer across the full width on `xs` screens. Actually, even with the first commit, there were some issues left on small screens (mobile phones for instance). This is a way to fix them.
=> Footer on small screens

deposit/views.py, requirements.txt, upload/views.py
This adds a rate limit on the deposit endpoint, to make sure we don't flood our target repositories.
=> Limit deposit rates to 200 / day per IP

provisioning/provision.sh
Hi,
Here is a quick and dirty fix for the failures of Vagrant provisioning.
* I'm using `set -e` to stop the script at the first error and `set -x` to have a verbose output and ease debugging (prints the command ran before running it).
* Some `gdal` libraries were missing, these are now installed through `apt`.
* There was a weird bug with the `setuptools` install which I solved by first uninstalling `setuptools` and reinstalling it. Not exactly sure where this is coming from and this is quite a dirty patch, but it works.
Is there any known issues with Dissemin and Debian Stretch? Might be interesting to update the box used in Vagrant config to have a more up to date Debian.
Best,
=> Fix Vagrant provisioning script

autocomplete/views.py
See https://sentry.io/dissemin/dissemin/issues/744452148/?query=is%3Aunresolved
=> Fix an issue when no affiliations can be found

requirements.txt
See https://nvd.nist.gov/vuln/detail/CVE-2019-3498
=> Unpin Django version in requirements.txt for security updates

requirements.txt
=> Drop czipfile requirement

deposit/zenodo/protocol.py, deposit/zenodo/tests.py
Hi,
I guess this should fix #424. I added a test, but I'm not exactly sure how to run it locally :/ So definitely needs a review or some testing before merging.
Best,
=> Return a better error message when a paper is already present on Zenodo

papers/static/papers/refresh.js
=> More readable and better error message for skipped papers

requirements.txt
=> Update django-allauth to latest version.

deposit/forms.py, deposit/models.py, dissemin/urls.py, notification/models.py, notification/urls.py, notification/views.py, papers/models.py, papers/templates/papers/paperList.html, papers/templates/papers/search.html, papers/tests/test_ajax.py, papers/tests/test_pages.py, papers/views.py, publishers/models.py, publishers/templates/publishers/list.html, publishers/templates/publishers/policy.html, requirements-dev.txt, requirements.txt, statistics/templates/statistics/headers.html, templates/dissemin/skeleton.html, upload/forms.py, upload/models.py, upload/tests/test_views.py
This adds compatibility with Django 2 and probably drops compatibility with Django 1.11.
Closes #573.
=> Migrate to Django 2

.travis.yml
Compiling messages can fail (per #605) so we should check that in Travis too. The risk is that translatewiki.net updates will break the build, but that's something we need to be aware of. If this problem arises then we might look into asking Translatewiki to use PRs (if possible) or switch to Weblate which supports that.
=> Compile localization messages in travis, cache virtualenv

papers/templates/papers/group.html, papers/templates/papers/index.html, papers/templates/papers/institution.html, papers/templates/papers/paper.html, papers/templates/papers/search.html, publishers/templates/publishers/list.html, publishers/templates/publishers/policy.html, templates/dissemin/root_skeleton.html, templates/dissemin/skeleton.html
This should fix #13.
Note that this is **not** working and to be considered a WIP, because Django does not let us reuse a block twice in a template (`headTitle` block in `skeleton.html` template). 
I had a not so nice workaround (https://github.com/phretor/django-repeatblock) but it does not seem to be compatible with Django2 anyways.
@wetneb Feel free to take over and merge if you have a ready to use way to overcome the `headTitle` repetition. :)
=> WIP - Add meta OpenGraph tags

deposit/forms.py, deposit/hal/tests.py, deposit/osf/tests.py, deposit/tests/test_protocol.py, deposit/zenodo/tests.py
=> Update wrap_with_prefetching_status for Django 2.

doc/sphinx/install.rst
@Phyks recommended to add more explanations regarding the systemd units for celery and celerybeat and to include auto restart.
=> More details for installation of celery and celerybeat as daemons

provisioning/provision.sh
=> Update VM provisioning after #612

papers/templates/papers/department.html
See https://sentry.io/organizations/dissemin/issues/900885392/?project=189330&query=is%3Aunresolved&statsPeriod=14d&utc=true
The department page is no longer working. https://dissem.in/department/18/ rises an internal server error for instance.
I just deleted the `addResearcher` JS function since I could not find any matching URL or pattern / form in the code. I might have missed something.
=> Fix Sentry issue 189330

papers/tests/test_pages.py, papers/urls.py, papers/views.py
https://sentry.io/organizations/dissemin/issues/894371243/?project=189330&query=is%3Aunresolved&statsPeriod=14d&utc=true.
Should be fixed I think, according to https://github.com/dissemin/dissemin/blob/master/papers/urls.py#L33-L34.
=> Fix Sentry issue

backend/crossref.py, backend/maintenance.py, papers/models.py
Some more profiling could be done, but that is a start.
=> Small performance tweaks for Crossref ingestion

papers/forms.py, papers/views.py
This is a work in progress for solving #514.
Nothing is broken (yet :p) but the further filtering on ORCIDs is not working.
Estimated time: about one - two hours.
=> Search by ORCID, #514

dissemin/settings/common.py
=> Use thousands separator, very quick fix for #630.

backend/oadoi.py, papers/models.py
Various tweaks to try to speed up paper ingestion.
=> Paper ingestion optimization for speed

papers/templates/papers/publiListItem.html, papers/templates/robots.txt, templates/dissemin/skeleton.html
=> Add rel=nofollow to various links, update robots.txt

backend/oai.py, deposit/hal/metadata.py, deposit/hal/tests.py, deposit/protocol.py, papers/ajax.py, papers/forms.py, papers/models.py, papers/views.py
WIP, I should review this and outcome of tests first.
For the record, it addresses https://app.codacy.com/app/dissemin/dissemin/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJQeXRob24iXX0seyJpZCI6IkNhdGVnb3J5IiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJFcnJvciJdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbbnVsbF19XQ==.
=> Fix Codacy major errors

deposit/hal/protocol.py, deposit/hal/tests.py
These unrelated tests are failing on master too, so I am going to go ahead and merge.
=> Issue 654: HAL encoding

papers/api.py, papers/baremodels.py, papers/bibtex.py, papers/static/main.js, papers/templates/papers/paperDetails.html, papers/tests/test_api.py
This introduces an "Export citation" link in the right hand side bar in the paper detail page
Still quite a proof of concept.
=> First draft of individual paper export, see #186.

papers/forms.py
Would deserve a second look as this is changing the search logic.
This should make "FirstName LastName" the same as "LastName FirstName" and solve #516.
Estimated Time: 15 minutes.
=> Fix issue 516

papers/models.py
https://sentry.io/dissemin/dissemin/issues/871750601/?query=is%3Aunresolved
Note: Paper was https://dissem.in/p/2761246/semaphorin-3a-is-an-endogenous-angiogenesis-inhibitor-that-blocks-tumor-growth-and-normalizes-tumor-vasculature-in-transgenic-mouse-models. Username is at the end of sentry report.
=> Fix a SEntry reported error

papers/templates/papers/paper.html
Adds the year in front of authors list as "Article published in 2019 by Max Mustermann"
This PR changes some po-files, should I commit these too or is there another workflow for dissemin?
Closes #633
=> Date on paper page

dissemin/settings/common.py, dissemin/settings/dev.py, dissemin/settings/prod.py, doc/sphinx/install.rst
=> Better loglevels

papers/api.py, papers/baremodels.py, papers/static/style/style.css, papers/templates/papers/paperDetails.html, papers/tests/test_api.py
=> New BibTeX export modal

deposit/static/css/deposit.css, deposit/templates/deposit/start.html, papers/static/style/style.css, upload/static/libs/upload.js, upload/templates/upload/widget.html
Should fix #657 and fix #382.
Remaining point is that the JS validation of the form is not yet done. Actually, the form is validated server side with Django, it's a bit more work to handle this. We can open a separate issue to track this, it would probably require using http://emadmokhtar.com/client-side-validation-for-django-forms.html.
=> Better depositing UX

papers/templates/papers/search.html
=> Rename "authors" field to "co-authors" in Researcher view

Vagrantfile, dissemin/settings/common.py, dissemin/settings/dev.py, provisioning/provision.sh, requirements.txt
<s>WIP status since I have to recheck full build.</s>
=> Update VM config to Stretch

papers/urls.py, papers/views.py
=> Fix JSON bug when going back to results

papers/templates/papers/authorList.html, papers/templates/papers/search.html, papers/templatetags/orcid.py
=> Issue 660 tooltip for orcid badge

dissemin/settings/common.py, requirements.txt
Closes #608 
I am not sure if the commit itself is enough for the tracking. The sentry documentation is not very clear about that.
=> Tell sentry current commit

doc/sphinx/api.rst, papers/api.py, papers/tests/test_api.py
=> Fix and document the /api/query endpoint.

papers/urls.py, papers/views.py
This should solve the issue #716 about search and refetch from ORCID broken.
Tested against researcher page. **Untested** against "my profile" page, due to #721 :/
=> Fix issue #716: refetch and search not working on researchers page

papers/forms.py, papers/static/style/style.css, papers/templates/papers/advanced_search.html, papers/templates/papers/index.html, papers/templates/papers/paper.html, papers/templates/papers/paperDetails.html, papers/templates/papers/paperList.html, papers/templates/papers/paperSources.html, papers/templates/papers/search.html, publishers/templates/publishers/list.html, publishers/templates/publishers/policy.html, statistics/templates/statistics/pie_without_object.html, templates/dissemin/details.html, templates/dissemin/faq.html, templates/dissemin/login.html, templates/dissemin/partners.html, templates/dissemin/skeleton.html, templates/dissemin/sources.html, templates/dissemin/tos.html
=> Fix some accessibility issues

.gitignore, deposit/schema/conftest.py, deposit/schema/dissemin_v1.0.xsd, deposit/schema/fixtures/dissemin_v1.0.xml, deposit/schema/tests.py, doc/sphinx/add_your_own_repository.rst, doc/sphinx/configure_repository.rst, doc/sphinx/development.rst, doc/sphinx/index.rst, doc/sphinx/repositories.rst, doc/sphinx/writing_new_repository_interface.rst
A version for the metadata schema and documentation that was mentioned in the web conference.
=> Dissemin non-bibliographic metadata schema

papers/views.py
Hi,
I *think* this should fix both #721 and #745. As far as I understood, it seems the issue is coming from the fact that in the `pre_social_login` hook, the user is not already created in the Django database (https://github.com/dissemin/dissemin/blob/master/papers/views.py#L78-L79).
Therefore, the created researcher was never associated with the user profile and this association was not happening afterwards.
I splitted the hook in two parts, a `pre_social_login` part to create the `Researcher` object and abort the login in case of any error and a "post login" part to match the `Researcher` with the `User`.
=> Fix issue #745: ORCID names

deposit/admin.py, deposit/forms.py, deposit/hal/protocol.py, deposit/models.py, deposit/osf/protocol.py, deposit/protocol.py, deposit/zenodo/protocol.py
This adds a dropdown without changing any logic of registration.
Do we need tests for this? I am not even sure, how to perform them after all.
=> Dropdown for Repo-Protocol

deposit/admin.py, deposit/views.py
As discussed in the web conference we add
=> Deposit Logging

conftest.py, deposit/forms.py, deposit/models.py, deposit/templates/deposit/start.html, deposit/tests/conftest.py, deposit/tests/test_user_preferences.py, deposit/tests/test_views.py, deposit/views.py, doc/sphinx/testing.rst
Closes #767.
* Hides disabled repositories from users
* Disabled means disabled. 
* Some nice extendable fixtures 
This PR has translations.
=> Issue 767 Disabled Repos

deposit/sword/protocol.py, doc/sphinx/add_your_own_repository.rst, doc/sphinx/examples/mods/book-chapter_adaptive_multiagent_system_for_multisensor_maritime_surveillance.xml, doc/sphinx/examples/mods/journal-article_a_female_signal_reflects_mhc_genotype_in_a_social_primate.xml, doc/sphinx/examples/mods/other_assisting_configuration_based_feature_model_composition.xml, doc/sphinx/examples/mods/proceedings-article_activitycentric_support_for_weaklystructured_business_processes.xml, doc/sphinx/examples/mods/proceedings-article_an_efficient_vofbased_rans_method_to_capture_complex_sea_states.xml, doc/sphinx/examples/mods/reference-entry_chromatin_interaction_analysis_using_pairedend_tag_sequencing.xml, requirements.txt
=> Language detection for MODS

deposit/sword/protocol.py, doc/sphinx/add_your_own_repository.rst, doc/sphinx/examples/mods/poster_development_of_new_gpe_conjugates_with_application_in_neurodegenerative_diseases.xml, doc/sphinx/examples/mods/proceedings-article_cursos_efa.xml
=> Adding ORCID to MODS

templates/dissemin/partners.html
=> Include logo of OpenIng project

deposit/protocol.py, deposit/sword/conftest.py, deposit/sword/protocol.py, deposit/sword/tests.py
Adds support for ingesting the sword statement.
=> Ingest SWORD statement in SWORD METS protocol

deposit/sword/protocol.py, deposit/sword/tests.py, deposit/templates/deposit/start.html
Some fixes in SWORD protocol.
Besides of these, it worked very well in real tests :)
=> Sword fixes

.travis.yml, doc/sphinx/localization.rst, locale/qqq/LC_MESSAGES/django.po
The `qqq` locale should not be needed at runtime so it is not worth compiling it.
=> Fix compilation issue due to qqq locale

papers/static/style/mobile.css, papers/static/style/style.css, papers/templates/papers/index.html
* Header was too large on mobile device
* Partners images were not readable on green background
=> Fix minor issues with the start page

deposit/models.py, deposit/static/css/deposit.css, deposit/templates/deposit/start.html
Some enhancements to the repository description.
=> Enhance Repository Description

papers/templates/papers/advanced_search.html, papers/templates/papers/paper_list.html, papers/templates/papers/search_base.html, papers/templatetags/statuses.py, publishers/forms.py, publishers/templates/publishers/list.html, publishers/templates/publishers/publisher.html, website/static/js/dissemin.js, website/static/scss/custom.scss, website/static/scss/dissemin.scss, website/templates/dissemin/faq.html, website/templates/dissemin/start_page.html, website/templates/footer.html
Some things have to be changed:
=> Bootstrap4 - Final fixes

deposit/views.py, website/static/js/dissemin.js
The solution is much simpler than stated in #873, since only the form had to be rendered differently and the old form has to be replaced by the new html.
Closes #873
=> Issue 873 - Deposit Form Validation

papers/templates/papers/paper.html, papers/views.py
This includes:
* Notification for embargoed deposits
* Removal of splash url for pending/embargoed deposits
Closes #740
=> Improvements on deposit alerts

deposit/sword/protocol.py, deposit/sword/tests.py, doc/sphinx/libraries/technical_scope.rst
=> Deliver original filename in SWORD METS package

website/templates/dissemin/tos.html, website/tests/test_views.py, website/urls.py, website/views.py
This is required by GEANT
The guideline: https://wiki.refeds.org/display/CODE/Privacy+policy+guidelines+for+Service+Providers
Inspired by: https://arche.acdh.oeaw.ac.at/browser/privacy
The privacy policy must be available and english and may available in other languages. Currently I have not marked the strings for translation because I think it's maybe not too easy to translate.
=> Extended data privacy section

conftest.py, deposit/views.py, dissemin/settings/prod.py, website/middleware.py, website/tests/test_middleware.py
During some more testing a few things turned out to work not as expected.
=> Shibboleth adjustments
