backend/orcid.py, papers/utils.py
From a discussion with @wetneb over IRC, we agreed that the function was really too complex and difficult to make sense of it.
I propose this change which attempts to improve drastically readability of the process.
I would like to unify the creation of paper under the `DataPaper` interface, but I need more time to figure out if it is really a good idea or not.
For now, I think that it's fair enough to move on, and fix some "critical" bugs.
=> Refactor papers fetching from ORCiD profile

papers/templates/papers/search.html, papers/testpages.py
@RaitoBezarius  I have added a guard to your JS block: it should only be run when we are looking at a researcher's profile (the search.html template is used for any view where we need to display publication lists, which includes many other cases, see `papers/views.py`).
=> Fix papers/templates/papers/search.html

papers/static/style/style.css
In order to enforce the style, we put a `max-width: 750px` on the `#summaryLists` container, and to not let the long title overflow on the right container, we apply: `word-wrap: break-word;` on `.pubText p` (so that neither authors, neither title, neither references can overflow).
The result is the following:
(The long title is wrapped on the next line so you can still read it easily.)
Will close #268.
=> Long titles should increase the size of the summary list

papers/static/style/style.css, papers/templates/papers/publiListItem.html
Resolves #171
Now looks like this:
=> Separate download button from publisher

.travis.yml, backend/papersource.py, backend/pubtype_translations.py, backend/romeo.py, backend/tasks.py, backend/utils.py, dissemin/settings/travis.py, dissemin/testsettings.py, papers/ajax.py, papers/models.py, papers/testajax.py, papers/urls.py, papers/views.py
Using `CELERY_ALWAYS_EAGER`, we can fake tasks (they are executed directly in the process that spawns them. For this, we needed to get rid of `send_task` which is not affected by this feature. This was the occasion to remove some unused tasks.
=> Run tests without Celery

provisioning/provision.sh
I had to install libffi-dev and upgrade the python's setuptools in order to get the Vagrant deployment working.
Everything else worked out of the box!
=> libffi-dev installation and python's setuptools upgrade added to provision.sh 

autocomplete/__init__.py, autocomplete/forms.py, autocomplete/models.py, autocomplete/urls.py, autocomplete/views.py, autocomplete/widgets.py, deposit/forms.py, deposit/hal/forms.py, deposit/hal/metadata.py, deposit/hal/protocol.py, deposit/templates/deposit/start.html, dissemin/settings/common.py, dissemin/urls.py, requirements.txt, templates/dissemin/skeleton.html
(do not merge)
It uses the current user who is depositing to check the affiliations.
If no affiliation is found, we report it appropriately.
We have to use `idno` to get the ID of each affiliation which is given.
Todo : 
Refer to #248 for more information.
=> Minimal affiliation field with autocompletion for HAL

deposit/hal/protocol.py, deposit/hal/tests.py
And more generally, always try to return a verbose error message when HAL returns a 400 error code.
Closes #356.
P.S.: I am not really sure how I could test it :/ So this is untested for the moment.
=> Add a more explicit error message when paper is already in HAL

papers/static/style/style.css, papers/templates/papers/publiListItem.html
Class `.pubText` is blocked by Easyliste-FR starting from recently.
Dissemin was missing a lot of text blocks when uBlock/AdBlock is
enabled.
=> Fix Dissemin (and @wetneb's browser)

dissemin/settings/common.py, requirements.txt
Add Sentry's error reporting.
I'll add the necessary keys (on dissem.in and sandbox maybe) by myself once it's merged.
(if no key is specified, it won't interfere / throw an error / fail / crash / burn your house, no worries.)
[Here the reference for Django](https://docs.sentry.io/clients/python/integrations/django/)
Theorically, keys should be added in `secrets.py`.
I should document this… :smile: 
Also, once I get approval from sentry.io for open source Sentry, I'll enable GitHub auth through the Dissemin org, so that everyone in the org can access to the Sentry Dissemin's org.
=> Support for Sentry

backend/crossref.py, backend/testcrossref.py, dissemin/settings/common.py, papers/baremodels.py, papers/doi.py, papers/templatetags/doi.py, papers/testnames.py, papers/tests.py
Doi.org asks to systematically substitute doi.org to dx.doi.org
Source: https://hyp.is/M9Lj0GjaEeeB4idO26hqow/www.doi.org/factsheets/DOIProxy.html
=> [enh] replace dx.doi.org by doi.org

deposit/hal/metadata.py, deposit/hal/protocol.py, deposit/hal/tests.py
It is in the list of their topics but their deposit does not seem to accept it, so we remove it from our form.
=> Forbid "OTHER" topic in HAL form

deposit/zenodo/tests.py, dissemin/settings/secret_template.py, dissemin/settings/travis.py, requirements.txt
This does not break compatibility with Django 1.10, it's just nice to have support for server-side cursors in our postgres connection.
=> Move to Django 1.11

deposit/osf/protocol.py
Per https://developer.osf.io/#operation/preprints_create
https://github.com/dissemin/dissemin/issues/537
=> Specify required type field in "preprints" OSF API

statistics/models.py
Do not show an error page when `aggregations` are not defined for a
search query. Typically for weird (SQL injection attempts) queries such
as
```
luis angel moreno anselmi" or (1,2)=(select*from(select name_const(CHAR(111,108,111,108,111,115,104,101,114),1),name_const(CHAR(111,108,111,108,111,115,104,101,114),1))a) -- "x"="x
```
Fixes https://sentry.io/dissemin/dissemin/issues/309734257/.
=> Fix an issue with search results

deposit/osf/protocol.py, deposit/zenodo/protocol.py
Hi,
`extract_domain` returns `None` if no domain is matched. This lead to
exceptions being raised
https://sentry.io/dissemin/dissemin/issues/470352188/.
Not sure what is the value of `r.splash_url` [here](https://github.com/dissemin/dissemin/blob/master/deposit/zenodo/protocol.py#L57). There might be an extra bug with either this `r.splash_url` being an invalid URL or `extract_domain` failing to extract the domain. Not sure how to check this :/
Best,
=> Fix error when trying to deposit paper with invalid record URL

papers/bibtex.py, papers/testbibtex.py, requirements.txt
Hi,
This makes use of an updated version of Python-bibtexparser in order to
defer accents parsing to it. Accents should now be correctly parsed in
names.
I added some tests, hoping to cover these cases.
This is a fix for #362.
=> Fix issues with accents in the ORCID interface

papers/testpages.py, papers/views.py
Should fix latest SEntry notification, if I did not mess up with Django URLs.
=> Fix incorrect redirection when no HTTP REFERER (sic) is provided

provisioning/provision.sh
Remaining issue:
```
$ python /dissemin/manage.py update_index
/dissemin/.vm_venv/lib/python3.4/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
""")
Indexing 4 publishers
[ERROR/MainProcess] Failed indexing 1 - 4 (retry 5/5): Invalid template library specified. ImportError raised when trying to load 'papers.templatetags.choice_tags': bad magic number in 'papers.templatetags.choice_tags': b'\x03\xf3\r\n' (pid 7670): Invalid template library specified. ImportError raised when trying to load 'papers.templatetags.choice_tags': bad magic number in …
```
=> Fix Vagrant VM after migration to Python3

doc/sphinx/deploying.rst
Sorry, I missed some typos in the doc (missing trailing `_`).
=> Fix typos in the doc

doc/sphinx/deploying.rst, doc/sphinx/install.rst, doc/sphinx/localization.rst, doc/sphinx/repository_interfaces.rst
With the migration to Python3 and Django2 there were some documentation updates necessary.
Also concerning  #597 there is now a documentation for celery and celerybeat running as daemon.
=> More documentation

backend/tasks.py, statistics/models.py
and slow down the stats refreshing task.
This should fix the load issues.
=> Only update stats for publishers and all papers

dissemin/settings/common.py, statistics/templates/statistics/pie_without_object.html
My change from yesterday was actually too simple and was also affecting the years :/
I think the best approach is probably to default to not using thousands separators and explicitly force them for the statistics template. This PR should do it. However, I could not test it so not to be merged without explicitly checking it. I can check it and revise later.
=> Fix year formatting, no thousands separators

dissemin/settings/common.py, dissemin/settings/sphinx.py, publishers/romeo.py, publishers/tests/test_romeo.py
The RoMEO cache is no longer needed now that we fetch updates via their dump API.
=> Remove references to RoMEO cache

backend/crossref.py, backend/maintenance.py, backend/oadoi.py, backend/oai.py, backend/orcid.py, backend/tasks.py, backend/translators.py, backend/utils.py, deposit/models.py, deposit/registry.py, deposit/tasks.py, deposit/views.py, dissemin/celery.py, dissemin/fasttestrunner.py, dissemin/settings/common.py, dissemin/settings/dev.py, dissemin/settings/prod.py, papers/baremodels.py, papers/bibtex.py, papers/models.py, papers/name.py, papers/orcid.py, publishers/romeo.py, upload/forms.py
Tackling Issue #603. There is a logger for console, which is send in production to apache and everything that is a warning or higher should be sent to Sentry.
@Phyks Since you recently worked Sentry support, could you do that for the logs to? I Think that in `dissemin/settings/common.py` should be everything ready according to this documentation: 
https://docs.sentry.io/platforms/python/logging/#handler-classes
https://forum.sentry.io/t/sentry-python-dictconfig/5065/3
Also, not all print statements where removed, those from the tests, migrations and settings are still remaining:
```bash
$ grep -rn -e "\(\$\| \)print(" ./ --include=*py
./deposit/tests/test_protocol.py:131:            print(form.errors)
./deposit/tests/test_protocol.py:149:            print(self.proto._logs) …
```
=> WIP: Setting up logging

papers/static/papers/refresh.js
`Object.assign` is only defined in ES6, therefore not available in old browsers such as iOS 8, see https://sentry.io/organizations/dissemin/issues/954240591/?project=189330&query=is%3Aunresolved&statsPeriod=14d&utc=false.
jQuery has a `$.extend` (https://api.jquery.com/jQuery.extend/) which should do the trick everywhere.
=> Move ES6 syntax to jQuery syntax to avoid issues with old browsers

templates/dissemin/tos.html
Fix #652.
Given the current Apache conf, we are storing access and errors for 14 days. These include IP addresses as well as requested URL as far as I know. We also have the Sentry third-party (the only one we have I think), which is probably worth mentionning.
This PR updates the TOS accordingly
=> Improve TOS page

papers/templates/papers/paper.html
One (very) extreme example is 
https://dissem.in/p/3994958/combined-measurement-of-the-higgs-boson-mass-in-pp-collisions-at-root-s7-and-8-tev-with-the-atlas-and-cms-experiments
But more than 15 authors might happen from time to time, so a cutdown in the html title is fine, since it's you used as tab name.
=> Shorten Author List in Page Title

deposit/hal/protocol.py
Closes #668.
This also adds more logging if the deposit fails, so that the metadata is stored in the logs. In this case the XML was actually fine, the issue came from the Zip creation, but might encounter cases where AOfr validation genuinely fails.
=> Fix HAL zip creation.

backend/crossref.py, backend/oadoi.py, backend/tests/test_utils.py, backend/utils.py
This refactors a few things to add rate reporting to crossref and make it robust to 500 errors. A generic decorator to add rate reporting to a generator is introduced.
=> Make Crossref import more robust

papers/static/style/style.css, papers/templates/papers/paperList.html, templates/dissemin/faq.html
Here is a proposal to fix #529.
While researcher page remain untouched
Actually, there seemed to be a bug in the previous researcher code, preventing the "not found" text to be shown when there were multiple pages. Not sure whether this was on purpose?
=> Emphasize missing papers faq. Fix #529.

.travis.yml, backend/orcid.py, backend/tasks.py, backend/tests/test_orcid.py, papers/forms.py, papers/models.py, papers/search_indexes.py, requirements.txt
This changes the search index so that ORCID ids are directly indexed there.
We currently only index researcher ids (we don't have researchers for every ORCID profile, hence the discrepancy).
Tests are still needed and `link_existing_papers` needs to be hooked to the rest of the code for #659.
=> Index ORCID ids in Paper objects

papers/tests/test_ajax.py
Both tests where marked as to fail expected, but they no longer fail.
After merge rerun Travis CI in #775.
=> Ajax test with expected failure no longer fails

doc/sphinx/deploying.rst, provisioning/apache2-vhost.conf
This is an attempt at fixing https://github.com/dissemin/dissemin/issues/687. This would also provide users with a typical vhost to start from, to help them get starting hosting a Dissemin instance.
So far,
- We don't use any security HTTP headers (content security policy etc) on the production instance.
- We have a [B grade](https://www.ssllabs.com/ssltest/analyze.html?d=dissem.in) SSL score, part of the issues are easily fixable (the rest being difficult without dropping support for older browsers)
- We lack gzip and caching strategy for the static assets, see #687.
- We don't have CORS headers for the API, therefore preventing from using it from within the browser.
Note that this is a work in progress and currently untested :) Definitely not ready for a merge yet.
Left to do:
These are …
=> Add an example Apache2 vhost

templates/dissemin/root_skeleton.html
Seems changing the `max-width` for switching to the "mobile" layout is enough. I did not spot any bad side effects with this so far.
=> Fix #771, breakpoints mistake in CSS

deposit/hal/protocol.py
This is a quick fix - the real solution would be to migrate to `requests`, but I have already tried a few years ago and failed, so that is why I am going down this route this time.
Closes #794
=> Use HTTPS in HAL.

deposit/hal/protocol.py, deposit/hal/tests.py
Closes #801.
The Annif service should make it easy to add other classifiers for DDC, for instance.
=> HAL: Switch to Annif for topic prediction.

.travis.yml, conftest.py, doc/sphinx/testing.rst
By using vnu as server instead calling it via subprocess each time, we gain approximately 3 minutes per build.
In particular, calling `subprocess` often seems to make it slower. The reason is not known.
The main benefit it, that the Travis cron testing all languages should now finish in time and pass.
=> Accelerate html validation

deposit/views.py
Reduce number of queries when fetching upload page (from 39 to 28)
Some queries remain doubled, because some code is executed twice. Probably some JS thing.
=> Reduce number of queries when fetching upload page

deposit/conftest.py, deposit/protocol.py, deposit/sword/protocol.py, deposit/tests/test_protocol.py
The cached property was bound to SWORDMETSProtocol, but should be usable by all other protocols, if they like to.
Additionally, tests were missing.
=> Improvement of cached property publication

Vagrantfile, provisioning/provision.sh, utility/vbg-installer.rb
Hey,
trying to use vagrant to install dissemin, I ran into one issue with grub breaking the workflow (basically, some ncurses menu rendered as text during the installation). This was due to APT not being configured to use a non-interactive installation method, which this pull requests enable.
Rémy
=> Enables non-interactive frontend for APT

deposit/protocol.py, deposit/sword/protocol.py, deposit/sword/tests.py, deposit/tests/test_protocol.py, deposit/tests/test_utils.py, deposit/utils.py
This makes the creation of metadata way easier and clearer.
With `deposit.utils.MetadataConverter` you can get a flat dictionary with metadata from a paper and its OaiRecords.
You can give a preference, which OaiRecords to use first. If they do not have the information, the remaining will be used. This is per fields.
=> Deposit metadata improvements

backend/tests/test_zotero.py, backend/zotero.py, dissemin/settings/travis.py, dissemin/testsettings.py
Currently, the errors are not handled. This yields a 500 on the AJAX view from which we call the DOI cache server. In particular, the same error is logged multiple times.
Now we fetch and log them and give a proper return value (`None`).
Closes #867.
=> Handle doi cache zotero error

.travis.yml, requirements-dev.txt
Run test additionally on Python 3.7 and 3.8.
BTW: 3.5 drops out of support in September.
I wasn't able to switch to Bionic, since Elasticsearch 2.4.5 refused to run properly. It is possible to make ES 2.4.5 run on Bionic (this is the case on my dev virtual machine).
=> Run tests additionally on Python 3.7 and 3.8

.travis.yml
Travis complained about deprecated setting "sudo" as well as not having set an OS.
This fixes both and switches to bionic, since we touched the file anyway. Downside is, that we have to install ES 2.4.6 manually, but since it's horrible outdated, this is probably OK.
=> Use bionic and remove deprecated sudo

deposit/admin.py, deposit/hal/admin.py, papers/admin.py, papers/models.py, requirements.txt, upload/admin.py
Some of the admin sites were not usable, since we have to many model instances in our database. This is fixed by this PR, although we rarely need to inspect our instances in django admin.
The list of papers and oairecords has now a slightly misleading pagination (that does no errors). But this way we omit the 503 Gateway error, since otherwise a `select count(*) from` is performed, which takes too long.
Another new thing is that we can get from a paper object a list of its oairecords.
=> Enhance admin sites

deposit/templates/deposit/start.html, website/static/js/dissemin.js
UB Braunschweig mentioned, that one might think that chosen options on deposit page are not changable, since it might not be clear that one unfold an accordion element.
This PR simply adds the text "Change" to collapsed elements.
=> Hint that accordion elements on deposit page are collapsed

papers/models.py, papers/templates/papers/paper_panel.html
Currently we even show links/sources, where we have status 'rejected'. A
lot of pending records point to 404 pages, which is after all very
misleading.
There's still a box for pending or embargoed records on the paper detail
page.
=> Hide Oairecords if they have a deposit that is not available
